### ISSUE TITLE
import admit failing

### ISSUE THREAD

**Issue by mpound** [astroumd/admit#19]
Is there a pilot error below?

Tried a admit install from clean shell:

% env | grep -i admit
% env|grep PY
PYTHONBIN=/n/algol2/mpound/anaconda3/bin
% git clone https://github.com/astroumd/admit.git
% astromake
% astroload casa
% cd admit
% make config
autoconf
./configure
checking ADMIT config... checking for casa... /astromake/opt/casa/release/bin/casa
configure: Found CASA in /astromake/opt/casa/release
configure: Found a casa-root in or below /astromake/opt/casa/
checking CASA in /astromake/opt/casa/release (CASA_ROOT environment variable)... /astromake/opt/casa/release appears to be a valid CASA installation.2
configure: Using /astromake/opt/casa/release (CASA_ROOT environment variable)
checking for sphinx-build... yes
checking for dot... yes
configure: creating ./config.status
config.status: creating admit_start.csh
config.status: creating admit_start.sh
config.status: creating runadmit
% source admit_start.csh
% env|grep PY
PYTHONBIN=/n/algol2/mpound/anaconda3/bin
PYTHONPATH=/lupus4nb/mpound/admit
% casa --nologger
 casa --nologger

. =========================================
The start-up time of CASA may vary
depending on whether the shared libraries
are cached or not.
. =========================================

IPython 5.1.0 -- An enhanced Interactive Python.

CASA 5.4.0-68   -- Common Astronomy Software Applications

--> CrashReporter initialized.
Enter doc('start') for help getting started with CASA...
Using matplotlib backend: TkAgg

CASA <1>: import admit

. ---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-d11518699cd6> in <module>()
----> 1 import admit

ImportError: No module named admit

**Comment by teuben** [comment]
possibly pilot:   if you "import admit" from the $ADMIT directory you might
get this?
In other directories it should be ok though.

**Comment by mpound** [comment]
Hmm...cd /tmp before starting casa does indeed fix this.  Though that does not explain why I can sit in $ADMIT in my old tree and it works.    closing for now.
