### ISSUE TITLE
CubeSpectrum .tab file

### ISSUE THREAD

**Issue by leemundy** [astroumd/admit#41]
Currrently CubeSpectrum allows for making multiple spectra using pos= or sources=[]; however it only write how one spectrum to the .tab file.

Please enable CubeSpectrum to write out all requested spectral to the .tab file.

Thank you.

**Comment by teuben** [comment]
It now writes multiple files, named testCubeSpectrum_N.tab where N=0,1,2,...... as many as there are. This solved this issue, but does not solve #43 where the next run of CubeSpectrum overwrites (some of) these.

**Comment by teuben** [comment]
I'm closing this issue, since the solution is now given in #43
