### ISSUE TITLE
PVSlice drawing slice line at wrong angle?

### ISSUE THREAD

**Issue by mpound** [astroumd/admit#6]
PVSlice is drawing the slice line at a different angle that it did a several months ago. However, the resulting PV diagram appears the same.  So I conclude that there is an error in the drawing.  Looks like it is rotated by 90 degrees.     For a slit angle of 130:

admit.PVSlice_AT(alias='cubepv', slit=[291, 260, 400, 130], width=5), ['incube', 'insum'])

The first image is what was drawn in October, the second image is what was drawn today, the third images is the PV slice which is correct for the original slit location and unchanged today. 
![pvoverlay_thumb](https://user-images.githubusercontent.com/22331890/27694721-e223c87c-5cba-11e7-9335-e2f8d1f72fe4.png)
![june2017pvoverlay_thumb](https://user-images.githubusercontent.com/22331890/27694729-e88bdfc4-5cba-11e7-8e63-756415e55320.png)
![m16_12co7x4-cubepv pv_thumb](https://user-images.githubusercontent.com/22331890/27694745-f2df48c6-5cba-11e7-9cd0-7968f1f8930b.png)

**Comment by mpound** [comment]
This is with Casa version 4.7.2

**Comment by mpound** [comment]
Aha, note the y axis coordinate is now flipped from previous.  Before zero was at the top, now zero is at the bottom!

**Comment by mpound** [comment]
What I now think is going on is that PVSlice/Aplot are drawing the slice location as it is actually being computed, but the computation PA is wrong in the sense that it is "west of north" instead of "east of north."   It seems that impv gets this wrong and PVSlice/Aplot are correctly drawing the wrong slice.  I have concluded this by comparing with kpvslice. Note this is using the option slice=[xpos,ypos,pa] in PVSlice not feeding a segment in.

**Comment by mpound** [comment]
Ugh. Now I'm not so sure about my last comment.   APlot may be drawing it wrong (i.e. segment computed wrong by PVSlice) and impv may be computing the correct slice.

**Comment by mpound** [comment]
With slice=[x1,y1,x2,y2], the pv diagram is both made correctly and drawn correctly.  With slit=[x,y,length,PA] the pv diagram is made correctly but drawn incorrectly.  The line appears rotated by 90 degrees.   You should be able to verify this with NGC 253

**Comment by teuben** [comment]
yes, the edge on galaxy showed clearly the PA was  drawn 180-pa, perhaps a relic that I used 
    d1 = np.flipud(np.rot90 (data.reshape((nx,ny))))
at some point, despite that we use
    ax1.imshow(zoom, origin='lower')

But it's fixed now!

**Comment by mpound** [comment]
The angle is drawn correct now, but at the wrong center position.  You are still counting Y from the top.   At line 295 in PVSlice_AT.py:  
   ycen = ny-pvslit[1]-1
should be
  ycen = pvslit[1]

The attached image shows slit=[291, 260, 400, 130].   The star should be at x=291,y=260.   Clearly the 260 was counted from the top.   Also you deleted my star code, which I just added back in (maybe I never pushed originally). 

![m16_12co7x4-cubepv001 pv_overlay](https://user-images.githubusercontent.com/22331890/28795069-8bc299bc-7606-11e7-8af7-f5869223a893.png)

**Comment by teuben** [comment]
fixed, but there remains some situations where the moment of inertia does not see enough data for it to work reliably. this needs to be resolved (by me)

**Comment by mpound** [comment]
verified as resolved for non-MOI.
